version: "3"

services:
  web:
    image: sunnyw/node-app
    build: ./docker
    container_name: pitrix-dash
    ports:
      - "8000:8000"
    volumes:
      - .:/home/web/app
      - /home/web/app/node_modules
